import PersianCourseImage from '../assets/courses/talking-showing-app.jpeg'
import InheritanceCourseImage from '../assets/courses/inheritance-giving-money.jpeg'

const CourseList = [
    {
        id: 1,
        title: "Islamic Law of Inheritance",
        img: InheritanceCourseImage,
        categories: ["Islamic law", "Inheritance"],
        urlName: "islamic-law-of-inheritance",
        days: ["Monday", "Wednesday", "Friday"],
        scheduledOn: "August 18",
        timeOfDay: "7:00 PM",
        duration: "17 days",
        level: "Beginner",
        desc: "We are excited to teach you the core principles and key rules of Islamic inheritance law.",
        fullDesc: "Explore the Islamic Law of Inheritance and understand the principles guiding fair asset distribution. This course delves into preserving family harmony, ensuring justice, and reflecting ethical values. Gain insights into heir shares, their rationale, and the law's modern impact, enriching your knowledge of legal traditions and their contemporary relevance.",
        medium: "Zoom",
        courseFee: "3.59",
        enrolled: "0",
        lastUpdated: "19 hours ago",
        for: "For Islamic law students, professionals, and Muslims, beginner to advanced.",
        instructor: "Mufti Bilal Sabir",
        about: "This course provides an in-depth exploration of the Islamic Law of Inheritance, offering a comprehensive understanding of the principles and guidelines set forth in the Quran and Hadith. Students will delve into the intricacies of asset distribution, learning how Islamic law ensures justice, fairness, and family harmony. The course covers key concepts such as the shares of heirs, the rationale behind these shares, and the modern-day applications of these laws. Participants will also engage in practical exercises and case studies to solidify their understanding, making this course ideal for those seeking to deepen their knowledge of Islamic legal traditions and their relevance in contemporary society.",
        objectives: {
            obj1: 'Principles of inheritance law',
            obj2: 'Expert instruction from scholars',
            obj3: 'Real-life case studies',
            obj4: 'Legal and ethical insights',
            obj5: 'Interactive learning sessions',
        },
        materials: [
            "Comprehensive course notes",
            "Case studies and practical examples",
            "Access to recorded sessions",
            "Interactive quizzes and assignments",
            "Certificate of completion",
        ],
        requirements: [
            "Basic understanding of Islamic principles",
            "Interest in Islamic law",
            "Access to the internet",
        ],
        audience: [
            "Islamic law students",
            "Professionals in the field",
            "Muslims interested in inheritance laws",
        ],
        tags: [
            "Islamic Law",
            "Inheritance",
            "Shariah",
        ],
    },
    {
        id: 2,
        title: "Persian Language Course",
        img: PersianCourseImage,
        categories: ["Persian", "Language"],
        urlName: "persian-language-course",
        days: ["Tuesday", "Thursday", "Saturday"],
        scheduledOn: "September 11",
        timeOfDay: "7:00 PM",
        duration: "15 days",
        level: "Beginner",
        desc: "Achieve fluency and mastery with our Persian Language Course, covering grammar and vocabulary.",
        fullDesc: "Explore the captivating world of Persian with our comprehensive course. You'll master the script, engage in conversations, and journey through Persian grammar, vocabulary, and culture. By the end, you'll read, write, and communicate fluently, appreciating Persian heritage and enhancing your global opportunities.",
        medium: "Zoom",
        courseFee: "3.59",
        enrolled: "0",
        lastUpdated: "3 days ago",
        for: "For Persian language learners, from beginners to advanced.",
        instructor: "Mufti Bilal Sabir",
        about: "This Persian Language Course is designed to immerse you in the rich linguistic and cultural heritage of Persia. Starting with the basics, you will progress through a structured curriculum that covers essential grammar, vocabulary, and pronunciation. The course emphasizes practical communication skills, enabling you to engage in everyday conversations and understand Persian texts. In addition to language acquisition, you'll gain insight into Persian culture, literature, and history, enhancing your overall learning experience. Whether you're learning Persian for travel, academic purposes, or personal interest, this course provides a solid foundation and fosters a deep appreciation for the Persian language and its global significance.",
        objectives: {
            obj1: 'Fundamentals of Persian grammar',
            obj2: 'Professional teacher instruction',
            obj3: 'Conversational practice',
            obj4: 'Cultural and literary exploration',
            obj5: 'Multimedia learning resources',
            obj6: 'Personalized proficiency assessment',
        },
        materials: [
            "Persian grammar guide",
            "Audio and video lessons",
            "Practice worksheets",
            "Cultural immersion activities",
            "Certificate of completion",
        ],
        requirements: [
            "Interest in learning the Persian language",
            "Basic literacy skills",
            "Access to the internet",
        ],
        audience: [
            "Language enthusiasts",
            "Students learning Persian",
            "Anyone interested in Persian culture",
        ],
        tags: [
            "Persian",
            "Language",
            "Culture",
        ],
    },
]

export default CourseList;

